enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=aria2botsecret
rpc-allow-origin-all=true
dir=/workspace/aria2-bot/downloads
max-concurrent-downloads=5
continue=true
input-file=/workspace/aria2-bot/session.txt
save-session=/workspace/aria2-bot/session.txt
save-session-interval=60
