enable-rpc=true
rpc-listen-all=false
rpc-listen=127.0.0.1
rpc-listen-port=6800
rpc-secret=aria2botsecret
rpc-allow-origin-all=false
dir=downloads
max-concurrent-downloads=5
continue=true
input-file=session.txt
save-session=session.txt
save-session-interval=60
